#!/bin/bash

# Lincoln Teixeira Gomes - lincolnteixeiragomes@gmail.com
# apt-get install poppler-utils

serie=$1
week=$2
dir=$3

if [ "$dir" = "" ];then
    dir="$PWD"	
fi


if [ $# -eq 0 ]; then
   echo "Informe a serie!!"
   exit 0
fi

if [ ${#week} -eq 1 ]; then
   week="0${week}"
fi


if [ $serie -eq 1 ]; then
    subjects="arte educacao_fisica geografia historia lingua_portuguesa matematica biologia educacao_financeira filosofia fisica lingua_espanhola quimica sociologia"
elif [ $serie -eq 2 ]; then
    subjects="arte educacao_fisica geografia historia lingua_portuguesa matematica biologia educacao_financeira filosofia fisica lingua_espanhola quimica sociologia"
elif [ $serie -eq 3 ]; then
    subjects="arte educacao_fisica geografia historia lingua_portuguesa matematica biologia educacao_financeira filosofia fisica lingua_espanhola quimica sociologia"
elif [ $serie -eq 6 ]; then
    subjects="arte ciencias educacao_fisica ensino_religioso geografia historia lingua_inglesa lingua_portuguesa matematica"
elif [ $serie -eq 7 ]; then
        subjects="arte ciencias educacao_fisica ensino_religioso geografia historia lingua_inglesa lingua_portuguesa matematica"
elif [ $serie -eq 8 ]; then
    subjects="arte ciencias educacao_fisica geografia historia lingua_inglesa lingua_portuguesa matematica"
elif [ $serie -eq 9 ]; then
    subjects="arte ciencias educacao_fisica geografia historia lingua_inglesa lingua_portuguesa matematica"
else
    echo "Serie não cadastrada no momento!"
fi

echo ""
echo "Processing [$serie] grade [$week] week"
echo "------------------------------------------------------------------------------------------------------------------------"
for subject in $subjects; do   
    code=$(curl http://www.aulaparana.pr.gov.br/${subject}_${serie}ano 2> /dev/null | grep -B4 drive | grep -A4 Semana | egrep '(PDF para impress|Semana)' | sed 's/<p>//' | sed ':a; N; s/\n/ /; ta' | sed 's/<\/p>/\n/g' | awk '{print $1,$2,$8}' | awk 'NF>0' | grep "Semana ${week}" | awk -F"/" '{print $6}' | tail -1)
    if [ "$code" = "" ];then
        code=$(curl http://www.aulaparana.pr.gov.br/${subject}_${serie}serie 2> /dev/null | grep -B4 drive | grep -A4 Semana | egrep '(PDF para impress|Semana)' | sed 's/<p>//' | sed ':a; N; s/\n/ /; ta' | sed 's/<\/p>/\n/g' | awk '{print $1,$2,$8}' | awk 'NF>0' | grep "Semana ${week}" | awk -F"/" '{print $6}' | tail -1)
    fi
	if [ "$code" = "" ];then
	    echo "Problem to detect code for [$subject]"
		continue;
	fi
    echo "Downloading [https://docs.google.com/uc?export=download&id=$code] - [${subject^^}] "
    wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=$code' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=$code" -O /tmp/${subject}_serie${serie}_semana${week}.pdf 2>> /tmp/dulci.log && rm -rf /tmp/cookies.txt
done
echo "------------------------------------------------------------------------------------------------------------------------"

pdfunite $(ls /tmp/*[0-9].pdf 2> /dev/null) /tmp/ano${serie}_semana${week}_kit.pdf 2> /tmp/pdfunite.err && rm -f /tmp/*[0-9].pdf
retval_pdfunite=$?

if [ $retval_pdfunite -eq 0 ]; then
    mv /tmp/ano${serie}_semana${week}_kit.pdf $dir
    echo "This is your document - [${dir}/ano${serie}_semana${week}_kit.pdf]"
	evince ${dir}/ano${serie}_semana${week}_kit.pdf 
	
elif [ $retval_pdfunite -eq 99 ]; then
    echo ""
    echo "Something is wrong, please check this log:"
	echo "------------------------------------------"
    echo "Dont have documents to join."
else
    echo ""
    echo "Something is wrong, please check this log:"
	echo "------------------------------------------"
	grep -i semana /tmp/pdfunite.err && rm -f /tmp/pdfunite.err
fi
